/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Test;

import Datos.ClienteDAO;
import Domain.Cliente;
import javax.swing.JOptionPane;
import java.sql.*;
import Datos.Conexión;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author JPerez
 */
public class EliminaryModificar extends javax.swing.JInternalFrame {

    ClienteDAO cdao = new ClienteDAO();
    Cliente cliente;
    Connection conexion = null;
    Conexión instancia= Conexión.getInstance();
    
    public EliminaryModificar() {
        initComponents();
        this.setTitle("Eliminar o Modificar Clientes");
        jbeliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbseleccion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jlnombre = new javax.swing.JLabel();
        jtfsaldo = new javax.swing.JTextField();
        jlapellido = new javax.swing.JLabel();
        jlemail = new javax.swing.JLabel();
        jltelefono = new javax.swing.JLabel();
        jlsaldo = new javax.swing.JLabel();
        jtfapellido = new javax.swing.JTextField();
        jtfnombre = new javax.swing.JTextField();
        jtfemail = new javax.swing.JTextField();
        jtftelefono = new javax.swing.JTextField();
        jbmodificar = new javax.swing.JButton();
        jlmodificar = new javax.swing.JLabel();
        jbeliminar = new javax.swing.JButton();
        jtfid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbseleccion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jcbseleccion.setForeground(new java.awt.Color(21, 64, 78));
        jcbseleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modificar Cliente", "Eliminar Cliente" }));
        jcbseleccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 64, 78), 3, true));
        jcbseleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbseleccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbseleccionItemStateChanged(evt);
            }
        });
        jcbseleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbseleccionActionPerformed(evt);
            }
        });
        getContentPane().add(jcbseleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 16, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Que desea hacer? : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 19, -1, -1));

        jlnombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlnombre.setText("Nuevo Nombre");
        getContentPane().add(jlnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 99, -1, -1));

        jtfsaldo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfsaldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtfsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 230, 172, -1));

        jlapellido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlapellido.setText("Nuevo Apellido");
        getContentPane().add(jlapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 133, -1, -1));

        jlemail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlemail.setText("Nuevo Email");
        getContentPane().add(jlemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jltelefono.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jltelefono.setText("Nuevo Telefono");
        getContentPane().add(jltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jlsaldo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlsaldo.setText("Nuevo Saldo");
        getContentPane().add(jlsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jtfapellido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfapellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtfapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        jtfnombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 100, 170, -1));

        jtfemail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfemail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtfemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 170, 170, -1));

        jtftelefono.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtftelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtftelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 200, 172, -1));

        jbmodificar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbmodificar.setForeground(new java.awt.Color(21, 64, 78));
        jbmodificar.setText("Modificar");
        jbmodificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 64, 78), 3, true));
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 270, 90, 30));

        jlmodificar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlmodificar.setText("Digite el ID que desea modificar:");
        getContentPane().add(jlmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jbeliminar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbeliminar.setForeground(new java.awt.Color(21, 64, 78));
        jbeliminar.setText("Eliminar");
        jbeliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 64, 78), 3, true));
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 90, 40));

        jtfid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 60, 60, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbseleccionActionPerformed
        // TODO add your handling code here:7
        
    }//GEN-LAST:event_jcbseleccionActionPerformed

    private void jcbseleccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbseleccionItemStateChanged
        // TODO add your handling code here:
        String seleccion=(String) jcbseleccion.getSelectedItem();
        
        if(seleccion.equals("Modificar Cliente")){
            jlmodificar.setText("Digite el ID que desea Modificar");
            jlnombre.setVisible(true);
            jlapellido.setVisible(true);
            jlemail.setVisible(true);
            jltelefono.setVisible(true);
            jlsaldo.setVisible(true);
            jtfnombre.setVisible(true);
            jtfapellido.setVisible(true);
            jtfemail.setVisible(true);
            jtftelefono.setVisible(true);
            jtfsaldo.setVisible(true);
            jbmodificar.setVisible(true);
            jbeliminar.setVisible(false);
        }else if(seleccion.equals("Eliminar Cliente")){
            jlmodificar.setText("Digite el ID que desea Eliminar");
            jlnombre.setVisible(false);
            jlapellido.setVisible(false);
            jlemail.setVisible(false);
            jltelefono.setVisible(false);
            jlsaldo.setVisible(false);
            jtfnombre.setVisible(false);
            jtfapellido.setVisible(false);
            jtfemail.setVisible(false);
            jtftelefono.setVisible(false);
            jtfsaldo.setVisible(false);
            jbmodificar.setVisible(false);
            jbeliminar.setVisible(true);
        }
    }//GEN-LAST:event_jcbseleccionItemStateChanged

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
        // TODO add your handling code here:
        conexion = instancia.conectar();
        try {
            if(conexion.getAutoCommit()){
                conexion.setAutoCommit(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(EliminaryModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int idCliente = Integer.parseInt(jtfid.getText().trim());
        
        cliente = new Cliente(idCliente);
        
        int respuesta1=JOptionPane.showInternalConfirmDialog(null, "Esta usted seguro de eliminar este registro?");
        if(respuesta1==JOptionPane.YES_OPTION){
            cdao.eliminar(cliente);
            JOptionPane.showMessageDialog(null, "Cliente eliminado de los Registros");
        }else{
            JOptionPane.showMessageDialog(null, "La eliminacion de clientes ah sido cancelada....");
        }
        
        jtfid.setText("");
        
        try {
            conexion.rollback();
        } catch (SQLException ex) {
            Logger.getLogger(EliminaryModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed
        // TODO add your handling code here:
        conexion = instancia.conectar();
        try {
            if(conexion.getAutoCommit()){
                conexion.setAutoCommit(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(EliminaryModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
        int idCliente = Integer.parseInt(jtfid.getText().trim());
        String nombre = jtfnombre.getText().trim();
        String apellido = jtfapellido.getText().trim();
        String email = jtfemail.getText().trim();
        int telefono= Integer.parseInt(jtftelefono.getText().trim());
        float saldo = Float.parseFloat(jtfsaldo.getText().trim());
        
        cliente = new Cliente(idCliente, nombre, apellido, email, telefono, saldo);
        cdao.modificar(cliente);
        JOptionPane.showMessageDialog(null, "Cliente Modificado");
        
        jtfapellido.setText("");
        jtfnombre.setText("");
        jtftelefono.setText("");
        jtfsaldo.setText("");
        jtfemail.setText("");
        jtfid.setText("");
        
        try {
            conexion.rollback();
        } catch (SQLException ex) {
            Logger.getLogger(EliminaryModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbmodificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JComboBox<String> jcbseleccion;
    private javax.swing.JLabel jlapellido;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jlmodificar;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel jlsaldo;
    private javax.swing.JLabel jltelefono;
    private javax.swing.JTextField jtfapellido;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfnombre;
    private javax.swing.JTextField jtfsaldo;
    private javax.swing.JTextField jtftelefono;
    // End of variables declaration//GEN-END:variables
}
