package Test;

import Datos.ClienteDAO;
import Datos.Conexión;
import Domain.Cliente;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Registro extends javax.swing.JInternalFrame {

    ClienteDAO cdao = new ClienteDAO();
    Cliente cliente;
    Connection conexion = null;
    Conexión instancia= Conexión.getInstance();
    
    public Registro() {
        initComponents();
        this.setTitle("Registro");
    }
    
    private void limpiar(){
        jtfapellido.setText("");
        jtfnombre.setText("");
        jtftelefono.setText("");
        jtfsaldo.setText("");
        jtfemail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfnombre = new javax.swing.JTextField();
        jtfapellido = new javax.swing.JTextField();
        jtfemail = new javax.swing.JTextField();
        jtftelefono = new javax.swing.JTextField();
        jtfsaldo = new javax.swing.JTextField();
        jbregistrar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Digite su Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Digite su Apellido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 76, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Digite su Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 109, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Digite su Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 142, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Digite su Saldo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 175, -1, -1));

        jtfnombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jtfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 40, 172, -1));

        jtfapellido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfapellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtfapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 73, 170, -1));

        jtfemail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfemail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtfemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 106, 170, -1));

        jtftelefono.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtftelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtftelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 139, 172, -1));

        jtfsaldo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfsaldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtfsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 172, 172, -1));

        jbregistrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbregistrar.setForeground(new java.awt.Color(21, 64, 78));
        jbregistrar.setText("Registrar");
        jbregistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 64, 78), 3, true));
        jbregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 233, 97, 31));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregistrarActionPerformed
        // TODO add your handling code here:
        try {
            conexion = instancia.conectar();
            if(conexion.getAutoCommit()){
                conexion.setAutoCommit(false);
            }
            String nombre = jtfnombre.getText().trim();
            String apellido = jtfapellido.getText().trim();
            String email = jtfemail.getText().trim();
            int telefono = Integer.parseInt(jtftelefono.getText());
            float saldo = Float.parseFloat(jtfsaldo.getText());

            cliente = new Cliente(nombre, apellido, email, telefono, saldo);
            cdao.insertar(cliente);

            JOptionPane.showMessageDialog(null, "Cliente Registrado");
            conexion.commit(); 
            limpiar();
        } catch (HeadlessException | NumberFormatException e ) {
            System.out.println("error: " + e);
            try {
                conexion.rollback();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbregistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbregistrar;
    private javax.swing.JTextField jtfapellido;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JTextField jtfnombre;
    private javax.swing.JTextField jtfsaldo;
    private javax.swing.JTextField jtftelefono;
    // End of variables declaration//GEN-END:variables
}
