package Test;

import Datos.Conexión;
import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.sql.*;

public class TestCliente extends javax.swing.JFrame {

    Registro r;
    EliminaryModificar eym;
    Lista l;
    Conexión c = Conexión.getInstance();
    Connection conexion = null;
    public TestCliente() {
        r = new Registro();
        eym = new EliminaryModificar();
        l = new Lista();
        add(r);
        add(eym);
        add(l);
        initComponents();
        this.setTitle("Principal");
        this.setLocationRelativeTo(null);
        Usuario.setVisible(false);
        Contraseña.setVisible(false);
        jbcrear.setVisible(false);
    }
    
    private void registrarUsuario(){
        String password = String.valueOf(Contraseña.getPassword());
        
        if(password.equals("") || Usuario.getText().equals("")){
            while(Contraseña.getPassword().equals("") || Usuario.getText().equals("")){
                String user=JOptionPane.showInputDialog("Por favor digite el usuario");
                String pass=JOptionPane.showInputDialog("Por favor digite la contraseña");
                Usuario.setText(user);
                Contraseña.setText(pass);
            }
            
            //JOptionPane.showMessageDialog(null, "Ya puede registrar el usuario");
            
            try {
                Connection conectaramysql = c.conectar();
                PreparedStatement insercion = conectaramysql.prepareStatement("insert into registros(usuario,contraseña) values(?,?)");
                
                insercion.setString(1, Usuario.getText());
                insercion.setString(2, Contraseña.getText());
                insercion.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "¡¡Usuario Registrado!!");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Ocurrio un Error en el registro"+e);
            }
            
            Usuario.setText("");
            Contraseña.setText("");
            
        }else{
            try {
                Connection conectaramysql = c.conectar();
                PreparedStatement insercion = conectaramysql.prepareStatement("insert into registros(usuario,contraseña) values(?,?)");
                
                insercion.setString(1, Usuario.getText());
                insercion.setString(2, password);
                insercion.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "¡¡Usuario Registrado!!");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Ocurrio un Error en el registro"+e);
            }
            
            Usuario.setText("");
            Contraseña.setText("");            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Contraseña = new javax.swing.JPasswordField();
        jcbseleccion = new javax.swing.JComboBox<>();
        jbcrear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiRegistro = new javax.swing.JMenuItem();
        jmieliminaromodificar = new javax.swing.JMenuItem();
        jmiEnlistar = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        escritorio.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");

        Usuario.setBackground(new java.awt.Color(0, 102, 102));
        Usuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        Contraseña.setBackground(new java.awt.Color(0, 102, 102));
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });

        jcbseleccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbseleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perfil", "Crear Usuario", "Eliminar Usuario" }));
        jcbseleccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 255, 153)));
        jcbseleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbseleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbseleccionActionPerformed(evt);
            }
        });

        jbcrear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbcrear.setText("Registrar");
        jbcrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 153, 102), new java.awt.Color(51, 51, 0)));
        jbcrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jcbseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenu1.setText("Home");

        jMenuItem1.setText("Inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Control de Clientes");

        jmiRegistro.setText("Registro");
        jmiRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistroActionPerformed(evt);
            }
        });
        jMenu2.add(jmiRegistro);

        jmieliminaromodificar.setText("Eliminar o modificar");
        jmieliminaromodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmieliminaromodificarActionPerformed(evt);
            }
        });
        jMenu2.add(jmieliminaromodificar);

        jmiEnlistar.setText("Lista de Clientes");
        jmiEnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEnlistarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiEnlistar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEnlistarActionPerformed
        // TODO add your handling code here:
        r.setVisible(false);
        eym.setVisible(false);
        l.setVisible(true);
        escritorio.setVisible(false);
    }//GEN-LAST:event_jmiEnlistarActionPerformed

    private void jmiRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistroActionPerformed
        // TODO add your handling code here:
        r.setVisible(true);
        eym.setVisible(false);
        l.setVisible(false);
        escritorio.setVisible(false);
    }//GEN-LAST:event_jmiRegistroActionPerformed

    private void jmieliminaromodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmieliminaromodificarActionPerformed
        // TODO add your handling code here:
        r.setVisible(false);
        eym.setVisible(true);
        l.setVisible(false);
        escritorio.setVisible(false);
    }//GEN-LAST:event_jmieliminaromodificarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        r.setVisible(false);
        eym.setVisible(false);
        l.setVisible(false);
        escritorio.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void jcbseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbseleccionActionPerformed
        // TODO add your handling code here:
        String seleccion=(String) jcbseleccion.getSelectedItem();
        
        if(seleccion.equals("Crear Usuario")){
            Usuario.setVisible(true);
            Contraseña.setVisible(true);
            jbcrear.setVisible(true);
        }else if(seleccion.equals("Perfil")){
            Usuario.setVisible(false);
        Contraseña.setVisible(false);
        jbcrear.setVisible(false);
        }
    }//GEN-LAST:event_jcbseleccionActionPerformed

    private void jbcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcrearActionPerformed
        // TODO add your handling code here:
        registrarUsuario();
        JOptionPane.showMessageDialog(null, "Usuario Registrado");
    }//GEN-LAST:event_jbcrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

//            try {
//            UIManager.setLookAndFeel(new AluminiumLookAndFeel());
//        } catch (Exception e) {
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbcrear;
    private javax.swing.JComboBox<String> jcbseleccion;
    private javax.swing.JMenuItem jmiEnlistar;
    private javax.swing.JMenuItem jmiRegistro;
    private javax.swing.JMenuItem jmieliminaromodificar;
    // End of variables declaration//GEN-END:variables
}
