/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class PruebaEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form PruebaEncuesta
     */
    public PruebaEncuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        rbsuiza = new javax.swing.JRadioButton();
        rbcanada = new javax.swing.JRadioButton();
        rbrussia = new javax.swing.JRadioButton();
        rbseleccionar = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg1.add(rbsuiza);
        rbsuiza.setText("Suiza");
        rbsuiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsuizaActionPerformed(evt);
            }
        });

        bg1.add(rbcanada);
        rbcanada.setText("Canada");
        rbcanada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcanadaActionPerformed(evt);
            }
        });

        bg1.add(rbrussia);
        rbrussia.setText("Russia");

        rbseleccionar.setText("Seleccionar");
        rbseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbseleccionarActionPerformed(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbcanada)
                    .addComponent(rbrussia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbsuiza, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbseleccionar)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(rbsuiza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcanada)
                    .addComponent(rbseleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbrussia)
                .addGap(18, 18, 18)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbcanadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcanadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcanadaActionPerformed

    private void rbsuizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsuizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbsuizaActionPerformed

    private void rbseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbseleccionarActionPerformed
        // TODO add your handling code here:
        if(rbsuiza.isSelected()){
            JOptionPane.showMessageDialog(null, "Has Elegido Suiza");
            
            ImageIcon imagen= new ImageIcon("Suiza.jpg");
        JLabel e2=new JLabel();
        e2.setBounds(5, 20, 210,130);
        e2.setIcon( new ImageIcon(imagen.getImage().getScaledInstance
                    (e2.getWidth(), e2.getHeight(),Image.SCALE_SMOOTH)));
        //cambiar el tamaño de la imagen sin dañar la imagen misma
        //Panel.setVisible(true);
        Panel.add(e2);
        }else if(rbcanada.isSelected()){
            JOptionPane.showMessageDialog(null, "Has Elegido Canada");
            
            ImageIcon imagen= new ImageIcon("Canada.jpg");
        JLabel e2=new JLabel();
        e2.setBounds(5, 20, 210,130);
        e2.setIcon( new ImageIcon(imagen.getImage().getScaledInstance
                    (e2.getWidth(), e2.getHeight(),Image.SCALE_SMOOTH)));
        //cambiar el tamaño de la imagen sin dañar la imagen misma
        //Panel.setVisible(true);
        Panel.add(e2);
        }else if(rbrussia.isSelected()){
            JOptionPane.showMessageDialog(null, "Has Elegido Russia");
            
            ImageIcon imagen= new ImageIcon("Russia.jpg");
        JLabel e2=new JLabel();
        e2.setBounds(5, 20, 210,130);
        e2.setIcon( new ImageIcon(imagen.getImage().getScaledInstance
                    (e2.getWidth(), e2.getHeight(),Image.SCALE_SMOOTH)));
        //cambiar el tamaño de la imagen sin dañar la imagen misma
        //Panel.setVisible(true);
        Panel.add(e2);
        }
    }//GEN-LAST:event_rbseleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JRadioButton rbcanada;
    private javax.swing.JRadioButton rbrussia;
    private javax.swing.JButton rbseleccionar;
    private javax.swing.JRadioButton rbsuiza;
    // End of variables declaration//GEN-END:variables
}
