/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemahospital;

import com.mysql.cj.jdbc.Driver;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author JPerez
 */
public class PantallaRegistro extends javax.swing.JInternalFrame {
    Connection con;
    public PantallaRegistro() {
        initComponents();
        
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Si esta viendo esto, no funciono la conexion");
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jtfnombre = new javax.swing.JTextField();
        rbfemenino = new javax.swing.JRadioButton();
        jtfapellido = new javax.swing.JTextField();
        rbmasculino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jdcfechanacimiento = new com.toedter.calendar.JDateChooser();
        jtfid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbregistro = new javax.swing.JButton();

        jtfnombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfnombre.setText("Nombre");
        jtfnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EventoEnfoque(evt);
            }
        });

        Sexo.add(rbfemenino);
        rbfemenino.setText("Femenino");

        jtfapellido.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtfapellido.setText("Apellido");
        jtfapellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfapellidoFocusGained(evt);
            }
        });
        jtfapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfapellidoActionPerformed(evt);
            }
        });

        Sexo.add(rbmasculino);
        rbmasculino.setText("Masculino");
        rbmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmasculinoActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Registro Pacientes");

        jtfid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfid.setText("Ingrese N° de Documento");
        jtfid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnfocadoEvent(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Fecha de Nacimiento");

        jbregistro.setText("Registro");
        jbregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbmasculino)
                        .addGap(106, 106, 106)
                        .addComponent(rbfemenino))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addComponent(jdcfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jbregistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfemenino)
                    .addComponent(rbmasculino))
                .addGap(18, 18, 18)
                .addComponent(jbregistro)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfapellidoActionPerformed

    private void rbmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmasculinoActionPerformed

    private void jbregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregistroActionPerformed
        // TODO add your handling code here:
        int year= jdcfechanacimiento.getCalendar().get(Calendar.YEAR);
        int month= jdcfechanacimiento.getCalendar().get(Calendar.MONTH);
        int day= jdcfechanacimiento.getCalendar().get(Calendar.DAY_OF_MONTH);
        
        String fechanacimiento=""+year+"-"+month+"-"+day;
        
        String sexo="";
        
        if(rbmasculino.isSelected()){
            sexo="M";
        }if(rbfemenino.isSelected()){
            sexo="F";
        }
        
        
        try {
            con= DriverManager.getConnection("jdbc:mysql://localhost/sistemahospital","root","");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO pacientes VALUES('"+jtfid.getText()+"','"+jtfnombre.getText()+"','"+jtfapellido.getText()+"','"+fechanacimiento+"','"+sexo+"')");
        } catch (SQLException ex) {
            Logger.getLogger(PantallaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no se puede conectar");
        }
        
        JOptionPane.showMessageDialog(null, "El paciente fue registrado correctamente", "Registro",0);
    }//GEN-LAST:event_jbregistroActionPerformed

    private void EnfocadoEvent(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnfocadoEvent
        // TODO add your handling code here:
        jtfid.setText("");
    }//GEN-LAST:event_EnfocadoEvent

    private void EventoEnfoque(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EventoEnfoque
        // TODO add your handling code here:
        jtfnombre.setText("");
    }//GEN-LAST:event_EventoEnfoque

    private void jtfapellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfapellidoFocusGained
        // TODO add your handling code here:
        jtfapellido.setText("");
    }//GEN-LAST:event_jtfapellidoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbregistro;
    private com.toedter.calendar.JDateChooser jdcfechanacimiento;
    private javax.swing.JTextField jtfapellido;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfnombre;
    private javax.swing.JRadioButton rbfemenino;
    private javax.swing.JRadioButton rbmasculino;
    // End of variables declaration//GEN-END:variables
}
