package com.mycompany.almacen_alexa;


import java.sql.*;
import javax.swing.JOptionPane;

public class Consultar extends javax.swing.JInternalFrame {

    Conexion conectar = Conexion.getInstance();
    public Consultar() {
        initComponents();
        this.setTitle("Consultar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTextArea();
        jtfbuscar = new javax.swing.JTextField();
        jbbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        informacion.setColumns(20);
        informacion.setRows(5);
        jScrollPane1.setViewportView(informacion);

        jtfbuscar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfbuscar.setText("Id que quiere buscar");
        jtfbuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 255, 255), new java.awt.Color(51, 255, 204)));
        jtfbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfbuscarFocusGained(evt);
            }
        });
        jtfbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbuscarActionPerformed(evt);
            }
        });

        jbbuscar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbbuscar.setText("Buscar");
        jbbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Ver toda la información:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Consultar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jtfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jbbuscar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfbuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbuscarFocusGained
        // TODO add your handling code here:
        jtfbuscar.setText("");
    }//GEN-LAST:event_jtfbuscarFocusGained

    private void jtfbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        informacion.setText("");
        try {
            
            Connection conexion= conectar.conectar();
            PreparedStatement seleccionar=conexion.prepareStatement("SELECT * FROM productos");
            ResultSet consulta=seleccionar.executeQuery();
            
            while(consulta.next()){
                informacion.append(consulta.getString(1));
                informacion.append("   ");
                informacion.append(consulta.getString(2));
                informacion.append("   ");
                informacion.append(consulta.getString(3));
                informacion.append("   ");
                informacion.append(consulta.getString(4));
                informacion.append("   ");
                informacion.append(consulta.getString(5));
                informacion.append("   ");
                informacion.append(consulta.getString(6));
                informacion.append("\n");
            }
            
            conectar.cerrarConexion();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog
            (null, "Fallo la consulta a la base de datos por:"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
        // TODO add your handling code here:
        try {
            informacion.setText("");
            Connection conexion= conectar.conectar();
            PreparedStatement buscar=conexion.prepareStatement("SELECT * FROM productos WHERE codigo = ?");
            buscar.setString(1, jtfbuscar.getText().trim());
            
            ResultSet consulta = buscar.executeQuery();
            while (consulta.next()) {                
                informacion.append(consulta.getString(1));
                informacion.append("   ");
                informacion.append(consulta.getString(2));
                informacion.append("   ");
                informacion.append(consulta.getString(3));
                informacion.append("   ");
                informacion.append(consulta.getString(4));
                informacion.append("   ");
                informacion.append(consulta.getString(5));
                informacion.append("   ");
                informacion.append(consulta.getString(6));
                informacion.append("\n");
            }
            
            JOptionPane.showMessageDialog(null, "Datos Encontrados");
            conectar.cerrarConexion();
        } catch (Exception e) {
            System.out.println("Error"+e);
        }
    }//GEN-LAST:event_jbbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea informacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JTextField jtfbuscar;
    // End of variables declaration//GEN-END:variables
}
