package com.mycompany.almacen_alexa;
import java.sql.*;
import javax.swing.JOptionPane;
public class Modificar_y_Eliminar extends javax.swing.JInternalFrame {

    Conexion conectar = Conexion.getInstance();
    public Modificar_y_Eliminar() {
        initComponents();
        this.setTitle("Modificar y Eliminar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfmarca = new javax.swing.JTextField();
        jtfnombre = new javax.swing.JTextField();
        jtffecha = new javax.swing.JTextField();
        jtfvendidos = new javax.swing.JTextField();
        jtfadquiridos = new javax.swing.JTextField();
        jcbseleccion = new javax.swing.JComboBox<>();
        jtfid = new javax.swing.JTextField();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfmarca.setBackground(new java.awt.Color(244, 254, 252));
        jtfmarca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfmarca.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 255), new java.awt.Color(51, 255, 204)), "Marca del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        getContentPane().add(jtfmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 175, -1));

        jtfnombre.setBackground(new java.awt.Color(244, 254, 252));
        jtfnombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 255), new java.awt.Color(51, 255, 204)), "Nombre del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        getContentPane().add(jtfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 250, -1));

        jtffecha.setBackground(new java.awt.Color(244, 254, 252));
        jtffecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtffecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 255), new java.awt.Color(51, 255, 204)), "Fecha de Vencimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        getContentPane().add(jtffecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 90, 155, -1));

        jtfvendidos.setBackground(new java.awt.Color(244, 254, 252));
        jtfvendidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfvendidos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 255), new java.awt.Color(51, 255, 204)), "Productos Vendidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        getContentPane().add(jtfvendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, -1));

        jtfadquiridos.setBackground(new java.awt.Color(244, 254, 252));
        jtfadquiridos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfadquiridos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 255), new java.awt.Color(51, 255, 204)), "Productos Adquiridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        getContentPane().add(jtfadquiridos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, -1));

        jcbseleccion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jcbseleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modificar", "Eliminar" }));
        jcbseleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbseleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbseleccionActionPerformed(evt);
            }
        });
        getContentPane().add(jcbseleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 231, 101, -1));

        jtfid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtfid.setText("Digite el Id a Modificar");
        jtfid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 255, 255), new java.awt.Color(51, 255, 204)));
        jtfid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfidFocusGained(evt);
            }
        });
        getContentPane().add(jtfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 231, 142, -1));

        jb1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jb1.setText("Modificar");
        jb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 231, -1, -1));

        jb2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jb2.setText("Eliminar");
        jb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbseleccionActionPerformed
        // TODO add your handling code here:
        String seleccion=(String) jcbseleccion.getSelectedItem();
        
        if(seleccion.equals("Modificar")){
            jtfnombre.setVisible(true);
            jtfmarca.setVisible(true);
            jtffecha.setVisible(true);
            jtfvendidos.setVisible(true);
            jtfadquiridos.setVisible(true);
            jtfid.setText("Digite el ID a Modificar");
            jb1.setVisible(true);
            jb2.setVisible(false);
            
        }else if(seleccion.equals("Eliminar")){
            jtfnombre.setVisible(false);
            jtfmarca.setVisible(false);
            jtffecha.setVisible(false);
            jtfvendidos.setVisible(false);
            jtfadquiridos.setVisible(false);
            jtfid.setText("Digite el ID a Eliminar");
            jb1.setVisible(false);
            jb2.setVisible(true);
            
        }
    }//GEN-LAST:event_jcbseleccionActionPerformed

    private void jtfidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfidFocusGained
        // TODO add your handling code here:
        jtfid.setText("");
    }//GEN-LAST:event_jtfidFocusGained

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        try {
            Connection conexion = conectar.conectar();
            String id = jtfid.getText().trim();
            PreparedStatement modificar = conexion.prepareStatement("UPDATE productos SET nombre = ?, marca = ?, fecha_vencimiento = ?, productos_vendidos = ?, productos_adquiridos = ? WHERE codigo = " + id);
            modificar.setString(1, jtfnombre.getText().trim());
            modificar.setString(2, jtfmarca.getText().trim());
            modificar.setString(3, jtffecha.getText().trim());
            modificar.setInt(4, Integer.parseInt(jtfvendidos.getText().trim()));
            modificar.setInt(5, Integer.parseInt(jtfadquiridos.getText().trim()));
            modificar.executeUpdate();

            JOptionPane.showMessageDialog(null, "El id ah sido modificado"
                    + "\nModificacion Exitosa...");

            conectar.cerrarConexion();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conexion= conectar.conectar();
            PreparedStatement eliminar= conexion.prepareStatement("delete from productos WHERE codigo = ?");
            eliminar.setString(1, jtfid.getText().trim());
            eliminar.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Registro eliminado...");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JComboBox<String> jcbseleccion;
    private javax.swing.JTextField jtfadquiridos;
    private javax.swing.JTextField jtffecha;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfmarca;
    private javax.swing.JTextField jtfnombre;
    private javax.swing.JTextField jtfvendidos;
    // End of variables declaration//GEN-END:variables
}
