package com.mycompany.test;

public class Registrar extends javax.swing.JInternalFrame {

    public Registrar() {
        initComponents();
        this.setTitle("Registrar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtmarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtfechaV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtproductV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtproductA = new javax.swing.JTextField();
        jBtnregistrar = new javax.swing.JButton();
        jBtnreiniciar = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jTxtnombre.setText("Nombre");
        jTxtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtnombreFocusGained(evt);
            }
        });

        jLabel2.setText("Marca");

        jTxtmarca.setText("Marca");
        jTxtmarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtmarcaFocusGained(evt);
            }
        });
        jTxtmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtmarcaActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo");

        jLabel4.setText("Fecha Vencimiento");

        jLabel5.setText("Productos Vendidos");

        jTxtproductV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtproductVActionPerformed(evt);
            }
        });

        jLabel6.setText("Productos Adquiridos");

        jBtnregistrar.setText("Registrar");
        jBtnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnregistrarActionPerformed(evt);
            }
        });

        jBtnreiniciar.setText("Reiniciar");
        jBtnreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnreiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBtnregistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnreiniciar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtproductA))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtproductV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtfechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtfechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtproductV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtproductA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnregistrar)
                    .addComponent(jBtnreiniciar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtnombreFocusGained
        // TODO add your handling code here:
        jTxtnombre.setText("");
    }//GEN-LAST:event_jTxtnombreFocusGained

    private void jTxtmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtmarcaActionPerformed

    private void jTxtmarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtmarcaFocusGained
        // TODO add your handling code here:
        jTxtmarca.setText("");
    }//GEN-LAST:event_jTxtmarcaFocusGained

    private void jTxtproductVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtproductVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtproductVActionPerformed

    private void jBtnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnregistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnregistrarActionPerformed

    private void jBtnreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnreiniciarActionPerformed
        // TODO add your handling code here:
    jTxtCodigo.setText("");
    jTxtfechaV.setText("");
    jTxtmarca.setText("");
    jTxtnombre.setText("");
    jTxtproductA.setText("");
    jTxtproductV.setText("");
    
    }//GEN-LAST:event_jBtnreiniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnregistrar;
    private javax.swing.JButton jBtnreiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtfechaV;
    private javax.swing.JTextField jTxtmarca;
    private javax.swing.JTextField jTxtnombre;
    private javax.swing.JTextField jTxtproductA;
    private javax.swing.JTextField jTxtproductV;
    // End of variables declaration//GEN-END:variables
}
